### ISSUE TITLE
Tasks are not getting saved

### ISSUE THREAD

**Issue by JPsychotic** [chrisvel/tududi#33]
Hello 🙂 I set up tududi via docker compose. Login and creating a project and areas did work fine. But when creating a task, it does not get saved and "All tasks" is still empty.
Container logs do not show any error but client console does show some:
![grafik](https://github.com/user-attachments/assets/30518ee2-6486-4697-bb71-47d80c19b0d8)

Some of the error messages are in german so I will translate them:

> Der Hash im "integrity"-Attribut hat die falsche Länge.

means

> The hash in the “integrity” attribute has the wrong length.

and

> Keine der "sha384"-Hashes im "integrity"-Attribut stimmen mit dem Inhalt der Subressource überein. Der > berechnete Hash ist [...].

means

> None of the “sha384” hashes in the “integrity” attribute match the content of the sub-resource. The calculated hash is [...].

Additionaly here's the compose file I used:
```
name: tududi
services:
    tududi:
        image: 'chrisvel/tududi:latest'
        container_name: tududi
        ports:
            - '16246:9292'
        volumes:
            - './data/db:/usr/src/app/tududi_db'
        environment:
            - TUDUDI_INTERNAL_SSL_ENABLED=false
            - TUDUDI_SESSION_SECRET=
            - TUDUDI_USER_PASSWORD=
            - TUDUDI_USER_EMAIL=
        restart: unless-stopped
```
Session secret, password and email were deleted because of security/privacy. The secret was created with `openssl rand -hex 64` like it was told in the readme.

If you need more info just tell me! Thanks in advance 🙂

**Comment by JPsychotic** [comment]
Ah I forgot to add:
Creating a task on the project overview page works. But creating the task via the floating action button does not work. The project search (the one when creating the task) does not work either and does not show the created project!

**Comment by chrisvel** [comment]
@JPsychotic sorry about that, I pushed a fix on `v0.32` or `latest`, can you please pull and check If it's fixed? 
The integrity issue is not important, I am also fixing it for v0.33.

**Comment by JPsychotic** [comment]
Hey! I tested the newest image and now I can create tasks via the floating action button, so thank you very much! 🙂

Sadly the project search still isn't working, should I create an extra issue for that?

**Comment by chrisvel** [comment]
oh, I was testing it on the update modal, I just saw that it doesn't show up the projects on new task creation one. No need to create a new issue, I'll patch it asap.

**Comment by chrisvel** [comment]
v0.33 is being pushed as we speak. Please check it out.

**Comment by chrisvel** [comment]
I am closing this issue as it appears to have been fixed. I have also opened another issue for the integrity thing. 
If saving a task is still a problem, please reopen. 
Thank you!
